### ISSUE TITLE
cloud game video analyzing

### ISSUE THREAD

**Issue by PIGzyj233** [vztu/COVER#2]
I now have a cloud gaming scenario. When the game is running, I capture the desktop and encode the video. I can save the video. It has very high requirements for the smoothness, picture restoration and fineness of the video. Do you think the existing model can analyze this kind of video? If I want to fine tune based on a small part of the video data I collected myself, do you have any good suggestions? Thank you very much

**Comment by vztu** [comment]
Thanks for the question.

1. Yes, it can. YouTube-UGC has a category of gaming videos, so the model has seen this type. If you want to see how it performs in gaming, you can try it on [LIVE-YT-Gaming](https://live.ece.utexas.edu/research/LIVE-YT-Gaming/index.html). But I'm guessing that it could be challenging to analyze very fine-grained aspects, as you mentioned, for all the VQA models, including ours.
2. If you only have a tiny dataset, I suggest that you fine-tune the MLP head; otherwise, you can fine-tune the entire model except the CLIP branch, just like our approach.

Hope this helps.

**Comment by PIGzyj233** [comment]
thanks
